  GNU nano 5.6                         /home/zax4r0/.vimrc                          Modified  
packadd! dracula
syntax enable
colorscheme dracula
set hidden
set nowrarp
set encoding=utf-8
set pumheilight=10
set fileencoding=utf-8
set ruler
set cmdheilight=2
set iskeyword+=-
set mouse=a
set splitbelow
set splitright
set t_Co=256
set conceallevel=0
set tabstop=2
set shiftwidth=2
set smarttab
set autoindent
set laststatus=0
set number
set cursorline
set showtabline=2
set noshowmode
set nobackup
set nowritebackup 
set updatetime=300
set timeoutline=100
set number
