#! /bin/sh

sxhkd &
compton &
#polybar example &
~/.config/polybar/launch.sh --hack
#~/.config/polybar/launch.sh --forest
#~/.config/polybar/launch.sh --shades
#~/.config/polybar.old/launch.sh
#~/.config/polybar/launch.sh --cuts
#~/.config/polybar/launch.sh --pwidgets
~/.fehbg
xrandr -s 1360x768

bspc monitor -d I II III IV

bspc config border_width        0 
bspc config window_gap          10
bspc config top_padding         37
bspc config normal_border_color "#0A0506"
bspc config active_border_color "#93555E"
bspc config focused_border_color "#CF0E1C"
bspc config presel_feedback_color "#ADA56A"

# bspc config automatic_scheme     spiral
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Code desktop='^3' follow=on
bspc rule -a Geany desktop='^3' follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a st-256color desktop='^1' follow=on

#notification
dunst -conf ~/.config/dunst/dunstrc &

#some 

nm-applet 

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
